import type { NextPage } from 'next'
import Head from 'next/head'
import LoginForm from './login/LoginForm'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Login TEST</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>login</h1>
      <LoginForm/>
    </div>
  )
}

export default Home
